### ISSUE TITLE
Possible issue with some non-english characters.

### ISSUE THREAD

**Issue by Chester-Southwood** [Aidurber/youtube-playlist-scraper#3]
When trying to grab information from a playlist of a chinese audio series, the "scrapePlaylist" function throws a unhandled promise exception "Error: Unable to parse body". 

From a small amount of testing, it seems there are some chinese characters that may cause this, as I tried a different playlist with chinese characters and it read successfully as intended.

Playlists with chinese characters successfully read:
* https://www.youtube.com/playlist?list=PL9ES2MCH3ulh8M34lhbg3zOrOKEhegP2g

Playlists with chinese characters unsuccessfully read:
* https://www.youtube.com/playlist?list=PL3rl4UOs2QOKLtpdogsDq7V_WAV-8P9Bd
* https://www.youtube.com/playlist?list=PLle97lwCzO_TYcemOOa7YFbxeDuxB9vdX

* 11/22/2020
After a little investigation locally, my assumption is most likely a red herring. Both playlists that didn't work are over 100 videos, while the one that worked was under 100 videos. Debugging I found that a exception was thrown "TypeError: Cannot read property 'videoId' of undefined" before throwing the user exception. This was thrown at the 100th item, possibly meaning that due to how youtube generates its playlist, it shows incomplete when the request is made resulting in this error.

**Comment by Aidurber** [comment]
@Chester-Southwood Thanks for the report. I'll try and find time to add a fix for this (as well as some tests, I just rushed this project out). I don't think it's possible to scrape paginated results, but erroring on 100 items isn't acceptible.

**Comment by Aidurber** [comment]
Hi @Chester-Southwood, sorry for the delay. As of version 1.0.4 it will no longer crash on a playlist over 100 videos. 

The problem remains of paginating results, but I don't think that's currently possible and other YouTube playlist scrapers face this issue.
