### ISSUE TITLE
Unable to parse initial data due to ;?

### ISSUE THREAD

**Issue by JetSimon** [Aidurber/youtube-playlist-scraper#6]
I am trying to scrape, nothing has changed in my code so I believe that youtube may have changed something last night?

It was working before.

Getting this message.

```
SyntaxError: Unexpected token ; in JSON at position 359440
    at JSON.parse (<anonymous>)
    at tryParseJson (/Users/ta/Documents/GitHub/Tubeify/node_modules/youtube-playlist-scraper/dist/youtube-playlist-scraper.js:51:17)
    at parseInitialData (/Users/ta/Documents/GitHub/Tubeify/node_modules/youtube-playlist-scraper/dist/youtube-playlist-scraper.js:63:10)
    at scrapePlaylist (/Users/ta/Documents/GitHub/Tubeify/node_modules/youtube-playlist-scraper/dist/youtube-playlist-scraper.js:68:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /Users/ta/Documents/GitHub/Tubeify/routes/index.js:62:9
Error: Unable to parse ytInitialData

**Comment by Aidurber** [comment]
@JetSimon It's still working for me, can you give me the ID of the playlist you're having an issue with?
Here's the result for my playlist: 
<img width="846" alt="CleanShot 2020-11-30 at 10 02 52@2x" src="https://user-images.githubusercontent.com/5732291/100595739-3aceb880-32f3-11eb-8313-ae0529db5974.png">

**Comment by JetSimon** [comment]
It is working now most of the time, but it still gives the odd error every once in awhile. I will let you know when it happens again. It seems like it will work for a playlist and then not work even when you do not change code and then work again.

So it must be something with youtube?

**Comment by Aidurber** [comment]
Yeah that sounds like a YT issue. I'll try and replicate it when I get a chance. Do you run the scraper frequently? I think YouTube has bot detection/mitigation if you use it heavily. Perhaps the reason I haven't seen any issue is my script runs once per hour.

**Comment by JetSimon** [comment]
I've been using it for this site I made. So the request amount is variable, it only requests once per use.

http://tubeify.app/

So not too frequent.

**Comment by Aidurber** [comment]
A new version is building, v2.1.0. This has added a user agent to the request. This can also be overridden by a new second argument to the scraper function. 

However, I highly recommend that you use the YouTube Data API for that, specifically the PlaylistItems resource. When your website starts to get more traffic, it will fail more frequently. See my remarks on limitations of scraping YouTube here: https://github.com/Aidurber/youtube-playlist-scraper#limitations. It's a little more work to use the YouTube API but it's better to depend directly on YouTube's public API than scraping.

**Comment by Hakej** [comment]
I have the same issue, but only when I'm hosting the app on Heroku. When I host app locally, everything works fine. Any ideas?

**Comment by Aidurber** [comment]
@Hakej Probably YouTube's bot detection. Again the same question, how frequently is the scraper called? You may be better off with the API in a production app.

**Comment by Hakej** [comment]
It is called very rarely because it didn't work for a couple of days already but works perfectly fine when I deploy the app locally.

**Comment by Aidurber** [comment]
Interesting, this is a stretch here but you try a different user agent [Scraper Options](https://github.com/Aidurber/youtube-playlist-scraper#options). 

If so many devs are having issues with this approach, it may not be fit for general use 🙁 

If I find some time, I'll put it on Heroku myself and try and debug.

**Comment by Hakej** [comment]
I'll give you an update on that - it stopped working locally as well. It worked yesterday locally but didn't work on the host, now it doesn't work anywhere.

**Comment by Aidurber** [comment]
@Hakej I could finally reproduce locally and managed to patch it. It's now live in version 2.1.1. YouTube changed the markup, I've added a more robust RegEx.

**Comment by Hakej** [comment]
It works great now, thank you.
